# Generated by Django 5.2.17 on 2026-09-23 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_ar',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='notification',
            name='destination',
            field=models.CharField(choices=[('NONE', 'None'), ('FACILITY', 'Facility'), ('OWNER_FACILITIES', "The owner's facilities")], default='NONE', max_length=24),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ar',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notifications_inbox_idx'),
        ),
    ]
