# Generated by Django 5.2.17 on 2026-09-28 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_province_map_center"),
        ("notifications", "0003_push_delivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_ar", models.CharField(max_length=180)),
                ("body_ar", models.CharField(max_length=400)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Every active account"),
                            ("OWNERS", "Facility owners and managers"),
                        ],
                        max_length=8,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.province",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"], name="notifications_bcast_idx"
                    )
                ],
            },
        ),
    ]
