# Generated by Django 5.2.17 on 2026-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory_sessions", "0002_rotation_security_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="mfa_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
