# Generated by Django 5.2.17 on 2026-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceSignal",
            fields=[
                (
                    "name",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("ok_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure", models.CharField(blank=True, max_length=60)),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
