from django.urls import path

from . import exports, views, views_content, views_duty, views_smart, views_tags

urlpatterns = [
    path("admin/me/", views.AdminMeView.as_view()),
    path("admin/dashboard/", views.DashboardView.as_view()),
    path("admin/tasks/", views_smart.TasksView.as_view()),
    path("admin/alerts/", views_smart.AlertsView.as_view()),
    path("admin/search/", views_smart.AdminSearchView.as_view()),
    path(
        "admin/facilities/<uuid:facility_id>/timeline/",
        views_smart.FacilityTimelineView.as_view(),
    ),
    path("admin/reports/bulk/", views_smart.ReportBulkDecisionView.as_view()),
    path("admin/rejection-templates/", views_smart.RejectionTemplateListView.as_view()),
    path(
        "admin/rejection-templates/<uuid:template_id>/",
        views_smart.RejectionTemplateDetailView.as_view(),
    ),
    path("admin/notifications/broadcast/", views_smart.BroadcastSendView.as_view()),
    path("admin/app-release/", views_smart.AppReleaseView.as_view()),
    path("admin/notifications/broadcasts/", views_smart.BroadcastHistoryView.as_view()),
    path(
        "admin/provinces/<uuid:province_id>/readiness/",
        views_smart.ProvinceReadinessView.as_view(),
    ),
    path("admin/analytics/staff/", views_smart.StaffAnalyticsView.as_view()),
    path("admin/ads/images/", views_smart.AdvertisementImageUploadView.as_view()),
    path("admin/exports/facilities.csv", exports.FacilitiesCsvView.as_view()),
    path("admin/exports/reports.csv", exports.ReportsCsvView.as_view()),
    path("admin/exports/audit.csv", exports.AuditCsvView.as_view()),
    path("admin/content/pages/", views_content.ContentPageListView.as_view()),
    path("admin/content/pages/<str:slug>/", views_content.ContentPageDetailView.as_view()),
    path("admin/content/faq/", views_content.FaqEntryListView.as_view()),
    path("admin/content/faq/<uuid:entry_id>/", views_content.FaqEntryDetailView.as_view()),
    path("admin/emergency-numbers/", views_content.EmergencyNumberListView.as_view()),
    path(
        "admin/emergency-numbers/<uuid:number_id>/",
        views_content.EmergencyNumberDetailView.as_view(),
    ),
    path("admin/contact-messages/", views_content.ContactMessageListView.as_view()),
    path(
        "admin/contact-messages/<uuid:message_id>/handle/",
        views_content.ContactMessageHandleView.as_view(),
    ),
    path("admin/duty/", views_duty.DutyRosterView.as_view()),
    path("admin/duty/<uuid:shift_id>/", views_duty.DutyShiftDetailView.as_view()),
    path("admin/applications/", views.ApplicationListView.as_view()),
    path("admin/applications/<uuid:application_id>/", views.ApplicationDetailView.as_view()),
    path(
        "admin/applications/<uuid:application_id>/approve/",
        views.ApplicationApproveView.as_view(),
    ),
    path("admin/applications/<uuid:application_id>/reject/", views.ApplicationRejectView.as_view()),
    path("admin/evidence/<uuid:evidence_id>/content/", views.EvidenceContentView.as_view()),
    path("admin/facilities/", views.FacilityListView.as_view()),
    path("admin/facilities/<uuid:facility_id>/", views.FacilityDetailView.as_view()),
    path("admin/facilities/<uuid:facility_id>/suspend/", views.FacilitySuspendView.as_view()),
    path("admin/facilities/<uuid:facility_id>/reactivate/", views.FacilityReactivateView.as_view()),
    path("admin/facilities/<uuid:facility_id>/close/", views.FacilityCloseView.as_view()),
    path("admin/users/", views.UserListView.as_view()),
    path("admin/users/<uuid:user_id>/", views.UserDetailView.as_view()),
    path("admin/users/<uuid:user_id>/block/", views.UserBlockView.as_view()),
    path("admin/users/<uuid:user_id>/unblock/", views.UserUnblockView.as_view()),
    path("admin/roles/", views.RoleListView.as_view()),
    path("admin/users/<uuid:user_id>/roles/", views.UserRolesView.as_view()),
    path("admin/category-groups/", views.CategoryGroupListView.as_view()),
    path("admin/category-groups/create/", views.CategoryGroupCreateView.as_view()),
    path("admin/category-groups/<uuid:group_id>/", views.CategoryGroupDetailView.as_view()),
    path("admin/categories/", views.CategoryListView.as_view()),
    path("admin/categories/create/", views.CategoryCreateView.as_view()),
    path("admin/categories/<uuid:category_id>/", views.CategoryDetailView.as_view()),
    path(
        "admin/categories/<uuid:category_id>/capabilities/",
        views.CategoryCapabilitiesView.as_view(),
    ),
    path("admin/categories/<uuid:category_id>/provinces/", views.CategoryProvinceView.as_view()),
    path(
        "admin/categories/<uuid:category_id>/specialties/",
        views_tags.CategorySpecialtiesView.as_view(),
    ),
    path(
        "admin/categories/<uuid:category_id>/service-tags/",
        views_tags.CategoryServiceTagsView.as_view(),
    ),
    path("admin/specialties/<int:specialty_id>/", views_tags.SpecialtyDetailView.as_view()),
    path(
        "admin/service-tags/<int:service_tag_id>/",
        views_tags.ServiceTagDetailView.as_view(),
    ),
    path("admin/provinces/", views.ProvinceListView.as_view()),
    path("admin/provinces/<uuid:province_id>/", views.ProvinceDetailView.as_view()),
    path("admin/provinces/<uuid:province_id>/cities/", views.ProvinceCityListView.as_view()),
    path(
        "admin/provinces/<uuid:province_id>/cities/<uuid:city_id>/",
        views.ProvinceCityDetailView.as_view(),
    ),
    path("admin/reports/", views.ReportListView.as_view()),
    path("admin/reports/<uuid:report_id>/resolve/", views.ReportDecisionView.as_view()),
    path("admin/reports/<uuid:report_id>/dismiss/", views.ReportDismissView.as_view()),
    path("admin/verification-requirements/", views.VerificationRequirementListView.as_view()),
    path(
        "admin/verification-requirements/<int:requirement_id>/",
        views.VerificationRequirementDetailView.as_view(),
    ),
    path("admin/ads/", views.AdvertisementListView.as_view()),
    path("admin/ads/<uuid:advertisement_id>/", views.AdvertisementDetailView.as_view()),
    path("admin/audit/", views.AuditListView.as_view()),
    path("admin/analytics/", views.AnalyticsView.as_view()),
    path("admin/settings/", views.SettingsView.as_view()),
    path("admin/system/status/", views.SystemStatusView.as_view()),
]
