# Generated by Django 5.2.17 on 2026-09-23 22:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('ABOUT', 'About us'), ('PRIVACY', 'Privacy policy'), ('TERMS', 'Terms and conditions'), ('INSTRUCTIONS', 'How to use the app'), ('FAQ', 'Frequently asked questions'), ('CONTACT', 'Contact us')], max_length=24)),
                ('title_ar', models.CharField(max_length=180)),
                ('body_ar', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'active'], name='content_legal_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='uniq_legal_key_version'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('key',), name='uniq_active_legal_document_per_key')],
            },
        ),
    ]
