# Generated by Django 5.2.17 on 2026-09-28 22:37

import content_services.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_services", "0003_seed_legal_documents"),
        ("locations", "0002_province_map_center"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_ar", models.CharField(max_length=300)),
                ("answer_ar", models.TextField(max_length=4000)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="kind",
            field=models.CharField(
                choices=[("LEGAL", "Legal"), ("FAQ", "FAQ"), ("PAGE", "Page")],
                default="PAGE",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="key",
            field=models.CharField(
                max_length=64, validators=[content_services.models._validate_page_key]
            ),
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.CharField(max_length=1000)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("OWNER", "Facility owner"),
                            ("CORRECTION", "Correction"),
                        ],
                        default="GENERAL",
                        max_length=16,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["handled_at", "-created_at"], name="content_contact_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_ar", models.CharField(max_length=120)),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[content_services.models._validate_dial_string],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("AMBULANCE", "Ambulance"),
                            ("FIRE", "Fire"),
                            ("POLICE", "Police"),
                            ("HOSPITAL", "Hospital"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("admin_note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_numbers",
                        to="locations.province",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label_ar"],
                "indexes": [
                    models.Index(
                        fields=["province", "active"], name="content_emergency_prov_idx"
                    )
                ],
            },
        ),
    ]
