# Generated by Django 5.2.17 on 2026-10-01 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_services', '0005_seed_page_kinds_emergency_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=16, unique=True)),
                ('minimum_version_code', models.PositiveIntegerField(default=0)),
                ('latest_version_code', models.PositiveIntegerField(default=0)),
                ('store_url', models.URLField(blank=True)),
                ('notice_ar', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['platform'],
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_version_code__lte', models.F('latest_version_code'))), name='content_app_release_minimum_not_above_latest')],
            },
        ),
    ]
