plugins {
    id("serva.android.application")
    id("serva.android.compose")
    id("serva.android.hilt")
    alias(libs.plugins.kotlin.serialization)
}

val apiBaseUrl = providers.gradleProperty("DIRECTORY_API_BASE_URL")
    .orElse("https://api.<ROOT_DOMAIN>/")
val mapStyleUrl = providers.gradleProperty("DIRECTORY_MAP_STYLE_URL")
    .orElse("https://maps.<ROOT_DOMAIN>/style.json")
val routingBaseUrl = providers.gradleProperty("DIRECTORY_ROUTING_BASE_URL")
    .orElse("https://<ROUTING_PROVIDER_HOST>/")
val geocodingBaseUrl = providers.gradleProperty("DIRECTORY_GEOCODING_BASE_URL")
    .orElse("https://<GEOCODING_PROVIDER_HOST>/")
val geocodingUserAgent = providers.gradleProperty("DIRECTORY_GEOCODING_USER_AGENT")
    .orElse("DirectoryPlatformAndroid/1")

android {
    defaultConfig {
        buildConfigField("String", "API_BASE_URL", "\"${apiBaseUrl.get()}\"")
        buildConfigField("String", "MAP_STYLE_URL", "\"${mapStyleUrl.get()}\"")
        buildConfigField("String", "ROUTING_BASE_URL", "\"${routingBaseUrl.get()}\"")
        buildConfigField("String", "GEOCODING_BASE_URL", "\"${geocodingBaseUrl.get()}\"")
        buildConfigField("String", "GEOCODING_USER_AGENT", "\"${geocodingUserAgent.get()}\"")
    }
}

dependencies {
    implementation(project(":core:model"))
    implementation(project(":core:network"))
    implementation(project(":core:database"))
    implementation(project(":core:datastore"))
    implementation(project(":core:auth"))
    implementation(project(":core:designsystem"))
    implementation(project(":core:location"))
    implementation(project(":core:maps"))
    implementation(project(":core:analytics"))
    implementation(project(":core:observability"))
    implementation(project(":feature:bootstrap"))
    implementation(project(":feature:home"))
    implementation(project(":feature:province"))
    implementation(project(":feature:search"))
    implementation(project(":feature:directory"))
    implementation(project(":feature:facility"))
    implementation(project(":feature:map"))
    implementation(project(":feature:navigation"))
    implementation(project(":feature:auth"))
    implementation(project(":feature:account"))
    implementation(project(":feature:ratings"))
    implementation(project(":feature:owner"))
    implementation(project(":feature:onboarding"))
    implementation(project(":feature:duty"))
    implementation(project(":feature:settings"))
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.androidx.core)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.hilt.lifecycle.viewmodel.compose)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.material3)
    debugImplementation(libs.androidx.compose.ui.tooling)
    testImplementation(libs.junit)
}
