"""Write the map from a clip's name to its compiled resource id.

    python apps/android/scripts/build-voice-clip-map.py

`Resources.getIdentifier(name, "raw", context.packageName)` cannot find these recordings. The
package it is handed is the application id, which every non-production build changes — the local
build is `com.servacode.directory.local` — while the resources are registered under the module's
namespace, `com.servacode.directory`. The lookup returns 0, `playClip` reports that there is no
recording, and guidance falls through to the device's synthesiser. On a phone with no Arabic voice
installed, which is most of them, that is silence. Nobody noticed because the production build is
the one flavour where the two strings happen to match.

So the names are resolved at compile time instead. A recording that is added, renamed or deleted
without this file being rebuilt is a compilation error rather than a trip that says nothing.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "feature/navigation/src/androidMain/res/raw"
OUT = (
    ROOT
    / "feature/navigation/src/androidMain/kotlin/com/servacode/directory/feature/navigation/NavigationClipResources.kt"
)

names = sorted(path.stem for path in RAW.glob("*.mp3"))
if not names:
    raise SystemExit(f"no recordings under {RAW}")

entries = "\n".join(f'    "{name}" to R.raw.{name},' for name in names)
OUT.write_text(
    f'''package com.servacode.directory.feature.navigation

/**
 * Every recording in the Arabic voice pack, by the name the planner asks for.
 *
 * GENERATED by `scripts/build-voice-clip-map.py` from `res/raw` — do not edit by hand.
 *
 * It exists because a name cannot be turned into a resource id at runtime here.
 * `Resources.getIdentifier` is handed the application id, which carries a suffix in every build but
 * production (`com.servacode.directory.local`), while these files are registered under the module's
 * namespace. The lookup found nothing, the fallback was the device's synthesiser, and a phone with
 * no Arabic voice — which is most of them — said nothing at all.
 *
 * {len(names)} recordings.
 */
internal val NAVIGATION_CLIPS: Map<String, Int> = mapOf(
{entries}
)
''',
    encoding="utf-8",
    newline="",
)
print(f"{len(names)} clips -> {OUT.relative_to(ROOT).as_posix()}")
