#!/usr/bin/env python3
"""Bind the map style to this deployment's map host (DECISION-082).

    python3 infrastructure/production/map/bind-style.py <origin> <archive.pmtiles> <out.json>

maps/raqqa.style.json is the one reference style; it names no host. This writes the style a
renderer reads, with:

* the tiles from Martin on <origin> (`/syria/{z}/{x}/{y}`), zoom range and bounds read from the
  archive itself, so a renderer overzooms past the last level instead of asking for tiles
  that do not exist;
* glyphs generated by Martin from the brand's IBM Plex Sans Arabic, which carries the Arabic
  presentation forms that MapLibre shapes letters into;
* the sprite built by Martin from maps/sprite/daliini;
* the reference's notes (keys starting with `_`) left out: they are for people, not renderers.

Layer ids are unchanged: the app inserts its route line and markers at the style's anchors.
"""
from __future__ import annotations

import json
import pathlib
import struct
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[3]
REFERENCE = ROOT / "maps" / "raqqa.style.json"
FONTS = {
    "RahalGo Regular": "IBM Plex Sans Arabic Regular",
    "RahalGo Bold": "IBM Plex Sans Arabic Bold",
}
SOURCE_ID = "syria"
SPRITE_ID = "daliini"


def archive_range(path: pathlib.Path) -> dict[str, Any]:
    """Zoom levels and bounds from a PMTiles v3 header."""
    with path.open("rb") as handle:
        header = handle.read(127)
    if header[:7] != b"PMTiles" or header[7] != 3:
        raise SystemExit(f"{path} is not a PMTiles v3 archive")
    min_lon, min_lat, max_lon, max_lat = struct.unpack_from("<iiii", header, 102)
    return {
        "minzoom": header[100],
        "maxzoom": header[101],
        "bounds": [round(v / 1e7, 5) for v in (min_lon, min_lat, max_lon, max_lat)],
    }


def without_notes(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: without_notes(v) for k, v in value.items() if not k.startswith("_")}
    if isinstance(value, list):
        return [without_notes(v) for v in value]
    return value


def bind(origin: str, archive: pathlib.Path) -> dict[str, Any]:
    origin = origin.rstrip("/")
    if not origin.startswith("https://") and not origin.startswith("http://"):
        raise SystemExit(f"the origin must be a URL: {origin}")
    style = without_notes(json.loads(REFERENCE.read_text(encoding="utf-8")))
    style["name"] = "Daliini"
    base = style["sources"]["base"]
    style["sources"]["base"] = {
        "type": "vector",
        "tiles": [f"{origin}/{SOURCE_ID}/{{z}}/{{x}}/{{y}}"],
        **archive_range(archive),
        "attribution": base["attribution"],
    }
    style["glyphs"] = f"{origin}/font/{{fontstack}}/{{range}}"
    style["sprite"] = f"{origin}/sprite/{SPRITE_ID}"
    for layer in style["layers"]:
        layout = layer.get("layout", {})
        if "text-font" in layout:
            fonts = layout["text-font"]
            unknown = [font for font in fonts if font not in FONTS]
            if unknown:
                raise SystemExit(f"layer {layer['id']} asks for fonts this host lacks: {unknown}")
            layout["text-font"] = [FONTS[font] for font in fonts]
    return style


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: bind-style.py <origin> <archive.pmtiles> <out.json>")
    origin, archive, out = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
    style = bind(origin, archive)
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(".tmp")
    temporary.write_text(json.dumps(style, ensure_ascii=False, indent=1), encoding="utf-8")
    temporary.replace(out)
    source = style["sources"]["base"]
    print(f"style: {out} (tiles z{source['minzoom']}-{source['maxzoom']}, {len(style['layers'])} layers)")


if __name__ == "__main__":
    main()
