# Generated by Django 5.2.17 on 2026-09-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_province_map_center"),
        ("pharmacy_duty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyshift",
            name="source",
            field=models.CharField(
                choices=[
                    ("OWNER", "Pharmacy owner or manager"),
                    ("ADMIN", "Platform operator"),
                    ("IMPORT", "Bulk import"),
                ],
                default="OWNER",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="DutyGapNudge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gap_date", models.DateField()),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_gap_nudges",
                        to="locations.province",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("province", "gap_date"),
                        name="uniq_duty_gap_nudge_per_day",
                    )
                ],
            },
        ),
    ]
