# Generated by Django 5.2.17 on 2026-10-03 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_province_map_center"),
        ("pharmacy_duty", "0002_duty_source_gap_nudges"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyRotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "facility_ids",
                    models.JSONField(default=list, help_text="Ordered facility ids."),
                ),
                ("starts_at_time", models.TimeField()),
                (
                    "ends_at_time",
                    models.TimeField(
                        help_text="At or before the start means the next morning."
                    ),
                ),
                ("per_day", models.PositiveSmallIntegerField(default=1)),
                ("anchor_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_rotations",
                        to="locations.province",
                    ),
                ),
            ],
        ),
    ]
