# Generated by Django 5.2.17 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('REGISTER', 'Register'), ('RECOVERY', 'Recovery'), ('PHONE_CHANGE', 'Phone change')], max_length=20),
        ),
    ]
