import uuid
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True; dependencies=[('locations','0001_initial')]
    operations=[
      migrations.CreateModel(name='CategoryGroup',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('code',models.CharField(max_length=80,unique=True)),('name_ar',models.CharField(max_length=120)),('name_en',models.CharField(blank=True,max_length=120)),('active',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0))]),
      migrations.CreateModel(name='Category',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('code',models.CharField(max_length=80,unique=True)),('slug',models.SlugField(max_length=100,unique=True)),('name_ar',models.CharField(max_length=120)),('name_en',models.CharField(blank=True,max_length=120)),('specialization',models.CharField(choices=[('GENERIC','Generic'),('PHARMACY','Pharmacy'),('DOCTOR','Doctor'),('NURSING','Nursing'),('MEDICAL_SUPPLIES','Medical supplies')],default='GENERIC',max_length=40)),('active',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0)),('group',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='categories',to='directory.categorygroup'))]),
      migrations.CreateModel(name='CategoryCapabilities',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('supports_hours',models.BooleanField(default=True)),('supports_photos',models.BooleanField(default=True)),('supports_ratings',models.BooleanField(default=True)),('supports_duty',models.BooleanField(default=False)),('supports_specialty_filter',models.BooleanField(default=False)),('supports_service_filter',models.BooleanField(default=False)),('supports_temporary_closure',models.BooleanField(default=True)),('supports_owner_onboarding',models.BooleanField(default=True)),('category',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='capabilities',to='directory.category'))]),
      migrations.CreateModel(name='CategoryProvince',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('public_enabled',models.BooleanField(default=False)),('owner_registration_enabled',models.BooleanField(default=False)),('sort_order',models.PositiveIntegerField(default=0)),('category',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='province_switches',to='directory.category')),('province',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='category_switches',to='locations.province'))]),
      migrations.CreateModel(name='VerificationRequirement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('label_ar',models.CharField(max_length=160)),('label_en',models.CharField(blank=True,max_length=160)),('instructions_ar',models.TextField(blank=True)),('instructions_en',models.TextField(blank=True)),('required',models.BooleanField(default=True)),('active',models.BooleanField(default=True)),('min_files',models.PositiveSmallIntegerField(default=1)),('max_files',models.PositiveSmallIntegerField(default=1)),('sort_order',models.PositiveIntegerField(default=0)),('category',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='verification_requirements',to='directory.category'))]),
      migrations.CreateModel(name='Specialty',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('specialization',models.CharField(blank=True,max_length=40)),('name_ar',models.CharField(max_length=120)),('name_en',models.CharField(blank=True,max_length=120)),('active',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0)),('category',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='specialties',to='directory.category'))]),
      migrations.CreateModel(name='ServiceTag',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name_ar',models.CharField(max_length=120)),('name_en',models.CharField(blank=True,max_length=120)),('active',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0)),('category',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='service_tags',to='directory.category'))]),
      migrations.AddConstraint(model_name='categoryprovince',constraint=models.UniqueConstraint(fields=('category','province'),name='uniq_category_province')),
    ]
