# Generated by Django 5.2.17 on 2026-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_province_map_centers"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorygroup",
            name="icon_key",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
