import uuid
from django.conf import settings
from django.contrib.gis.db import models
from django.db import migrations
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True; dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('locations','0001_initial'),('directory','0001_initial')]
    operations=[
      migrations.CreateModel(name='Facility',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('name_ar',models.CharField(max_length=160)),('name_en',models.CharField(blank=True,max_length=160)),('description_ar',models.TextField(blank=True)),('description_en',models.TextField(blank=True)),('phone',models.CharField(blank=True,max_length=16)),('address_ar',models.CharField(blank=True,max_length=255)),('address_en',models.CharField(blank=True,max_length=255)),('location',models.PointField(blank=True,null=True,srid=4326)),('status',models.CharField(choices=[('DRAFT','Draft'),('SUBMITTED','Submitted'),('ACTIVE','Active'),('REVERIFICATION_REQUIRED','Reverification required'),('SUSPENDED','Suspended'),('CLOSED','Closed')],default='DRAFT',max_length=40)),('activated_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='facilities',to='directory.category')),('city',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='locations.city')),('neighborhood',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='locations.neighborhood')),('province',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='facilities',to='locations.province'))]),
      migrations.CreateModel(name='FacilityMembership',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('OWNER','Owner'),('MANAGER','Manager')],max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('facility',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='memberships',to='facilities.facility')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='facility_memberships',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='FacilityApplication',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('kind',models.CharField(choices=[('INITIAL','Initial'),('REVERIFICATION','Reverification')],max_length=24)),('status',models.CharField(choices=[('DRAFT','Draft'),('SUBMITTED','Submitted'),('APPROVED','Approved'),('REJECTED','Rejected')],default='DRAFT',max_length=20)),('snapshot',models.JSONField(blank=True,default=dict)),('submitted_at',models.DateTimeField(blank=True,null=True)),('reviewed_at',models.DateTimeField(blank=True,null=True)),('rejection_reason',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('facility',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='applications',to='facilities.facility')),('reviewed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='+',to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='FacilityImage',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('storage_key',models.CharField(max_length=500,unique=True)),('sort_order',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('facility',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='images',to='facilities.facility'))]),
      migrations.CreateModel(name='VerificationEvidence',fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('storage_key',models.CharField(max_length=500,unique=True)),('created_at',models.DateTimeField(auto_now_add=True)),('facility',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='evidence',to='facilities.facility')),('requirement',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='+',to='directory.verificationrequirement'))]),
      migrations.AddConstraint(model_name='facilitymembership',constraint=models.UniqueConstraint(fields=('facility','user'),name='uniq_facility_member')),
      migrations.AddIndex(model_name='facility',index=models.Index(fields=['province','category','status'],name='facilities__prov_cat_status_idx')),
    ]
