# Generated by Django 5.2.17 on 2026-09-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_owner_media_integrity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facility',
            new_name='facility_prov_cat_status_idx',
            old_name='facilities__prov_cat_status_idx',
        ),
    ]
