# Generated by Django 5.2.17 on 2026-09-28 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_last_verified_at(apps, schema_editor):
    Facility = apps.get_model("facilities", "Facility")
    FacilityApplication = apps.get_model("facilities", "FacilityApplication")
    latest = (
        FacilityApplication.objects.filter(
            facility_id=models.OuterRef("pk"), status="APPROVED", reviewed_at__isnull=False
        )
        .order_by("-reviewed_at")
        .values("reviewed_at")[:1]
    )
    Facility.objects.update(last_verified_at=models.Subquery(latest))


class Migration(migrations.Migration):

    dependencies = [
        (
            "facilities",
            "0004_rename_facilities__prov_cat_status_idx_facility_prov_cat_status_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name="FacilityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("WRONG_INFO", "Wrong information"),
                            ("CLOSED_PERMANENTLY", "Closed permanently"),
                            ("WRONG_LOCATION", "Wrong location"),
                            ("WRONG_HOURS", "Wrong hours"),
                            ("NOT_ON_DUTY", "Not on duty"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="facilities.facility",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="facility_report_status_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_last_verified_at, migrations.RunPython.noop),
    ]
