# Generated by Django 5.2.17 on 2026-09-28 22:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0005_trust_whatsapp_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_ar", models.CharField(max_length=120)),
                ("body_ar", models.CharField(max_length=1000)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title_ar"],
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="hours_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="hours_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
