# Generated by Django 5.2.17 on 2026-10-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0007_seed_rejection_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityapplication",
            name="proposed_changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="facilityapplication",
            name="revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facilityapplication",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("REVERIFICATION", "Reverification"),
                    ("CHANGE", "Change"),
                ],
                max_length=24,
            ),
        ),
    ]
