# Generated by Django 5.2.17 on 2026-10-03 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0009_facility_invitations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityapplication",
            name="applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="verificationevidence",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claim_evidence",
                to="facilities.facilityapplication",
            ),
        ),
        migrations.AlterField(
            model_name="facilityapplication",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("REVERIFICATION", "Reverification"),
                    ("CHANGE", "Change"),
                    ("CLAIM", "Claim"),
                ],
                max_length=24,
            ),
        ),
    ]
